receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  docker_stats:
    endpoint: unix:///var/run/docker.sock
    collection_interval: 10s
    timeout: 5s

  hostmetrics:
    root_path: /hostfs
    collection_interval: 10s
    scrapers:
      cpu:
        metrics:
          system.cpu.logical.count:
            enabled: true
      disk: {}
      filesystem:
        metrics:
          system.filesystem.utilization:
            enabled: true
      load: {}
      memory:
        metrics:
          system.memory.utilization:
            enabled: true
          system.memory.limit:
            enabled: true
      network:
        metrics:
          system.network.connections:
            enabled: true
      paging: {}
      processes: {}

processors:
  resourcedetection:
    detectors: [env, system]
    timeout: 2s
    override: false

  batch:
    timeout: 1s

exporters:
  otlp_http:
    endpoint: http://lgtm:4318
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resourcedetection, batch]
      exporters: [otlp_http]
    metrics:
      receivers: [otlp, docker_stats, hostmetrics]
      processors: [resourcedetection, batch]
      exporters: [otlp_http]
    logs:
      receivers: [otlp]
      processors: [resourcedetection, batch]
      exporters: [otlp_http]
