{
 "title": "APM Dashboard",
 "description": "APM dashboard for monitoring OpenTelemetry-based services.  \n\nInstrument your applications using OpenTelemetry SDKs and send traces, metrics, and logs to Tempo for traces, a Prometheus-compatible database for metrics, and Loki for logs. This dashboard provides a centralized view of your application's health and performance. ",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Metrics", "query": "prometheus" },
   { "name": "tempo_datasource", "label": "Traces", "query": "tempo" },
   { "name": "loki_datasource", "label": "Logs", "query": "loki" },
   {
    "name": "service_name",
    "label": "Name",
    "query": {
     "query": "label_values(target_info{telemetry_sdk_name=~\".+\"},service_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "description": "service.name=${service_name}, ",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 0 },
   "options": {
    "content": "<h1><img src=\"https://opentelemetry.io/img/logos/opentelemetry-logo-nav.png\" alt=\"OpenTelemetry Icon\" width=\"25\" height=\"\"> Service ${service_name}</h1>\n"
   }
  },
  {
   "title": "Latest metrics received",
   "type": "stat",
   "description": "Shows the timestamp of the latest metrics received in the past 24h.",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "timestamp(sum by (deployment_environment_name, service_namespace, service_name) (target_info{service_name=\"$service_name\"}) or absent{})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Server RED Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "HTTP & RPC endpoints aggregation on the `http.server.request.duration` & `rpc.server.duration` metrics.\n\nSee https://opentelemetry.io/docs/specs/semconv/http/http-metrics/#metric-httpserverrequestduration and https://opentelemetry.io/docs/specs/semconv/rpc/rpc-metrics/#metric-rpcserverduration",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, deployment_environment_name, service_namespace, service_name) (\n    rate(\n      http_server_request_duration_seconds_bucket{\n        service_name=\"$service_name\"\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "HTTP p95"
    },
    {
     "expr": "avg by (deployment_environment_name, service_namespace, service_name) (\n  rate(\n    http_server_request_duration_seconds_sum{\n      service_name=\"$service_name\"\n    }[$__rate_interval]\n  )\n)\n/\navg by (deployment_environment_name, service_namespace, service_name) (\n  rate(\n    http_server_request_duration_seconds_count{\n      service_name=\"$service_name\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "HTTP avg"
    }
   ]
  },
  {
   "title": "Error",
   "type": "timeseries",
   "description": "HTTP and RPC endpoints aggregation on the `http.server.request.duration` and `rpc.server.duration` metrics. \n\nErrors are identified by : \n* `http.response.status_code=~\"5..\"`\n* `rpc.grpc.status_code!=\"0\"`\n\nSee https://opentelemetry.io/docs/specs/semconv/http/http-metrics/#metric-httpserverrequestduration\n",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n    (sum by(deployment_environment_name, service_namespace, service_name) (rate(http_server_request_duration_seconds_count{service_name=\"$service_name\", http_response_status_code=~\"5..\"}[$__rate_interval])) * 100) \n    / \n    sum by(deployment_environment_name, service_namespace, service_name) (rate(http_server_request_duration_seconds_count{service_name=\"$service_name\"}[$__rate_interval]))\n)\nor\n(\n    0\n    * \n    sum by(deployment_environment_name, service_namespace, service_name) (rate(http_server_request_duration_seconds_count{service_name=\"$service_name\"}[$__rate_interval]))\n)",
     "legendFormat": "HTTP 5xx errors"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "HTTP & RPC endpoints aggregation on the `http.server.request.duration` & `rpc.server.duration` metrics.\n\nSee https://opentelemetry.io/docs/specs/semconv/http/http-metrics/#metric-httpserverrequestduration",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "(sum(rate(http_server_request_duration_seconds_count{service_name=\"$service_name\"}[$__rate_interval])) by (deployment_environment_name, service_namespace, service_name)) ",
     "legendFormat": "HTTP requests"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 6, "w": 9, "x": 15, "y": 3 } },
  {
   "title": "Incoming HTTP requests",
   "type": "table",
   "description": "Inbound HTTP operations of the service (aka HTTP endpoints) based on the `http.server.request.duration` metric.\n\nErrors are identified by `http.response.status_code=~\"5..\"`.\n\nSee https://opentelemetry.io/docs/specs/semconv/http/http-metrics/#metric-httpserverrequestduration",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "\n        sum by (operation) (\n            label_join(\n                rate(http_server_request_duration_seconds_count{service_name=\"$service_name\"}[$__rate_interval]),\n                \"operation\",\n                \" \",\n                \"http_request_method\",\n                \"http_route\"\n            )\n        )\n    ",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "(\n        sum by (operation) (\n            label_join(\n                rate(http_server_request_duration_seconds_count{service_name=\"$service_name\", http_response_status_code=~\"5..\"}[$__rate_interval]),\n                \"operation\",\n                \" \",\n                \"http_request_method\",\n                \"http_route\"\n            )\n        )\n     / \n        sum by (operation) (\n            label_join(\n                rate(http_server_request_duration_seconds_count{service_name=\"$service_name\"}[$__rate_interval]),\n                \"operation\",\n                \" \",\n                \"http_request_method\",\n                \"http_route\"\n            )\n        )\n    ) or (0 * \n        sum by (operation) (\n            label_join(\n                rate(http_server_request_duration_seconds_count{service_name=\"$service_name\"}[$__rate_interval]),\n                \"operation\",\n                \" \",\n                \"http_request_method\",\n                \"http_route\"\n            )\n        )\n    )",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "\n        histogram_quantile(\n            0.99,\n            sum by (le, operation) (\n                label_join(\n                rate(http_server_request_duration_seconds_bucket{service_name=\"$service_name\"}[5m]),\n                \"operation\",\n                \" \",\n                \"http_request_method\",\n                \"http_route\"\n                )\n            )\n        )\n    ",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  { "title": "Outgoing client calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Outgoing HTTP requests",
   "type": "table",
   "description": "HTTP calls made by the service based on the `http.client.request.duration` metric.\n\nCalls broken done by remote `server.address` and by `http.request.method`.\n\nSee https://opentelemetry.io/docs/specs/semconv/http/http-metrics/#metric-httpclientrequestduration",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "\n        sum by (outbound_service) (\n            label_join(\n                rate(http_client_request_duration_seconds_count{service_name=\"$service_name\"}[$__rate_interval]),\n                \"outbound_service\",\n                \" \",\n                \"server_address\",\n                \"http_request_method\",\n                \"url_template\"\n            )\n        )\n    ",
     "legendFormat": "{{server_address}} {{http_request_method}} {{url_template}}"
    },
    {
     "expr": "(\n        sum by (outbound_service) (\n            label_join(\n                rate(http_client_request_duration_seconds_count{service_name=\"$service_name\", http_response_status_code=~\"5..\"}[$__rate_interval]),\n                \"outbound_service\",\n                \" \",\n                \"server_address\",\n                \"http_request_method\",\n                \"url_template\"\n            )\n        )\n     / \n        sum by (outbound_service) (\n            label_join(\n                rate(http_client_request_duration_seconds_count{service_name=\"$service_name\"}[$__rate_interval]),\n                \"outbound_service\",\n                \" \",\n                \"server_address\",\n                \"http_request_method\",\n                \"url_template\"\n            )\n        )\n    ) or (0 * \n        sum by (outbound_service) (\n            label_join(\n                rate(http_client_request_duration_seconds_count{service_name=\"$service_name\"}[$__rate_interval]),\n                \"outbound_service\",\n                \" \",\n                \"server_address\",\n                \"http_request_method\",\n                \"url_template\"\n            )\n        )\n    )",
     "legendFormat": "{{server_address}} {{http_request_method}} {{url_template}}"
    },
    {
     "expr": "\nhistogram_quantile(\n    0.99,\n    sum by (le, outbound_service) (\n        label_join(\n        rate(http_client_request_duration_seconds_bucket{service_name=\"$service_name\"}[5m]),\n        \"outbound_service\",\n        \" \",\n        \"server_address\",\n        \"http_request_method\",\n        \"url_template\"\n        )\n    )\n)",
     "legendFormat": "{{server_address}} {{http_request_method}} {{url_template}}"
    }
   ]
  },
  {
   "title": "DB client calls",
   "type": "table",
   "description": "DB calls made by the service based on the `db.client.operation.duration` metric.\n\nCalls broken down by `server.address` and `db.namespace`.\n\nSee https://opentelemetry.io/docs/specs/semconv/database/database-metrics/#metric-dbclientoperationduration\n",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (db_op, db_query_summary, database) (\n    label_join(\n        label_join(\n            rate(db_client_operation_duration_seconds_count{service_name=\"$service_name\"}[$__rate_interval]),\n            \"database\",\n            \"/\",\n            \"server_address\",\n            \"db_namespace\"\n        ),\n        \"db_op\",\n        \" | \",\n        \"database\",\n        \"db_query_summary\"\n    )\n)\n    ",
     "legendFormat": "{{server_address}} {{db_namespace}}"
    },
    {
     "expr": "(\n        sum by (db_op, db_query_summary, database) (\n            label_join(\n                label_join(\n                    rate(db_client_operation_duration_seconds_count{service_name=\"$service_name\", error_type!=\"\"}[$__rate_interval]),\n                    \"database\",\n                    \"/\",\n                    \"server_address\",\n                    \"db_namespace\"\n                ),\n                \"db_op\",\n                \" | \",\n                \"database\",\n                \"db_query_summary\"\n            )\n        )\n     / \n        sum by (db_op, db_query_summary, database) (\n            label_join(\n                label_join(\n                    rate(db_client_operation_duration_seconds_count{service_name=\"$service_name\"}[$__rate_interval]),\n                    \"database\",\n                    \"/\",\n                    \"server_address\",\n                    \"db_namespace\"\n                ),\n                \"db_op\",\n                \" | \",\n                \"database\",\n                \"db_query_summary\"\n            )\n        )\n    ) or (0 * \n        sum by (db_op, db_query_summary, database) (\n            label_join(\n                label_join(\n                    rate(db_client_operation_duration_seconds_count{service_name=\"$service_name\"}[$__rate_interval]),\n                    \"database\",\n                    \"/\",\n                    \"server_address\",\n                    \"db_namespace\"\n                ),\n                \"db_op\",\n                \" | \",\n                \"database\",\n                \"db_query_summary\"\n            )\n        )\n    )",
     "legendFormat": "{{server_address}} {{db_namespace}}"
    },
    {
     "expr": "\nhistogram_quantile(\n    0.99,\n    sum by (le, db_op, db_query_summary, database) (\n        label_join(\n            label_join(\n                rate(db_client_operation_duration_seconds_bucket{service_name=\"$service_name\"}[5m]),\n                \"database\",\n                \"/\",\n                \"server_address\",\n                \"db_namespace\"\n            ),\n            \"db_op\",\n            \" | \",\n            \"database\",\n            \"db_query_summary\"\n        )\n    )\n)",
     "legendFormat": "{{server_address}} {{db_namespace}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "type": "logs",
   "description": "Logs of the service, filtered by `service.name`, `service.namespace`, and `deployment.environment.name`.\n\nTo explore the logs, open the menu clicking on the icon `⋮` of this panel and click on `Explore`.",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"$service_name\"}"
    }
   ]
  },
  { "title": "Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "type": "table",
   "description": "Traces containing a span emitted by the service",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 43 },
   "targets": [
    {
     "query": "{resource.service.name=\"$service_name\"}",
     "limit": 20,
     "tableType": "traces"
    }
   ]
  }
 ]
}