otel_metrics_export:
  protocol: http/protobuf
  endpoint: http://otel-collector:4318
  interval: 5s
discovery:
  instrument:
    # to avoid OBI instrumenting ALL the processes in the host
    # (even the OTEL collector or the Docker services), we
    # explicitly enumerate here the containers of our tapas application
    - container_name: backend
    - container_name: frontend
    # - container_name: db
    # - container_name: lgtm
    # - container_name: otel-collector
